homeku/urls.py
from django.urls import path

from . import views

app_name = 'homeku'

urlpatterns = [
    path('', views.story1, name='index'),
]

pepeweskuy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homeku.urls')),
    path('', include('story3.urls')),
    path('', include('sutori5.urls'))
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
]

sutori5/urls.py
from django.urls import path

from . import views

app_name = 'sutori5'

urlpatterns = [
    path('project/', views.comingsoon, name='comingsoon'),
    path('delete/<int:idinput>', views.delete, name='delete'),
    path('detail/<int:id_detail>', views.detail, name='detail'),
]

homeku/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.
# - Nama Mata Kuliah
# - Dosen Pengajar
# - Jumlah SKS (number integer)
# - Deskripsi

class Jadwal(models.Model) :
    Matkul = models.CharField(max_length=120)
    Dosen = models.CharField(max_length=120)
    sks     = (('1','1'),
               ('2','2'),
               ('3','3'),
               ('4','4'),
               ('5','5'),
               ('6','6'),
               ('7','7'),)
    JumlahSKS = models.CharField(max_length = 20, choices = sks, default = '1',)
    Deskripsi = models.TextField(blank=False, null=False)
    ruangan = models.CharField(max_length=120, default="A204")
    CHOICES = (('Gasal 2019/2020','Gasal 2019/2020'),
               ('Genap 2018/2019','Genap 2018/2019'),
               ('Gasal 2018/2019','Gasal 2018/2019'),
               ('Genap 2017/2018','Genap 2017/2018'),
               ('Gasal 2018/2018','Gasal 2018/2018'),
               ('Genap 2016/2017','Genap 2016/2017'),
               ('Gasal 2016/2017','Gasal 2016/2017'),)
    
    semestertahun = models.CharField(max_length = 20, choices = CHOICES, default = '1',)
    
    



    

sutori5/models.py
from django.db import models

# Create your models here.
# - Nama Mata Kuliah
# - Dosen Pengajar
# - Jumlah SKS (number integer)
# - Deskripsi

class Jadwal(models.Model) :
    Matkul = models.CharField(max_length=120)
    Dosen = models.CharField(max_length=120)
    sks     = (('1','1'),
               ('2','2'),
               ('3','3'),
               ('4','4'),
               ('5','5'),
               ('6','6'),
               ('7','7'),)
    JumlahSKS = models.CharField(max_length = 20, choices = sks, default = '1',)
    Deskripsi = models.TextField(blank=False, null=False)
    ruangan = models.CharField(max_length=120, default="A204")
    CHOICES = (('Gasal 2019/2020','Gasal 2019/2020'),
               ('Genap 2018/2019','Genap 2018/2019'),
               ('Gasal 2018/2019','Gasal 2018/2019'),
               ('Genap 2017/2018','Genap 2017/2018'),
               ('Gasal 2018/2018','Gasal 2018/2018'),
               ('Genap 2016/2017','Genap 2016/2017'),
               ('Gasal 2016/2017','Gasal 2016/2017'),)
    
    semestertahun = models.CharField(max_length = 20, choices = CHOICES, default = '1',)
    
    



    

sutori5/forms.py
from django.forms import ModelForm
from .models import Jadwal
from django import forms

class Jadwalku(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = [
            'Matkul',
            'Dosen',
            'JumlahSKS',
            'Deskripsi',
            'ruangan',
            'semestertahun',
        ]

homeku/views.py
from django.shortcuts import render

# Create your views here.

def story1(request):
    return render(request, 'story1.html')

# Create your views here.


#Test template yang sesuai

story3/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect
# Create your views here.

def index(request):
    return render(request, 'index.html')
# Create your views here.


# def comingsoon(request):
    
#     formku = Jadwal.objects.all()
#     hasilku = Jadwalku(request.POST or None)  
#     context = {
#         'form' : formku,
#         'form_status':hasilku,
#     }

#     if request.method=='POST':
# 	    if hasilku.is_valid():
# 		    formku.create(
# 			    Dosen = hasilku.cleaned_data.get('Dosen'),
# 			    Matkul = hasilku.cleaned_data.get('Matkul'),
#                 JumlahSKS = hasilku.cleaned_data.get('JumlahSKS'),
#                 Deskripsi = hasilku.cleaned_data.get('Deskripsi'),
#                 semestertahun = hasilku.cleaned_data.get('semestertahun'),
#                 ruangan = hasilku.cleaned_data.get('ruangan'),
# 			    )

#     return render(request, 'comingsoon.html', context)

# def delete(request, idinput) :
#     Jadwal.objects.filter(id=idinput).delete()
#     return HttpResponseRedirect("/project")

# def detail(request, id_detail) :
#    id_matkul = Jadwal.objects.get(id=id_detail)
#    return render(request, 'detail.html', {'i': id_matkul})

sutori5/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import Jadwalku
from .models import Jadwal
from django.http import HttpResponseRedirect

# Create your views here.
def comingsoon(request):
    
    formku = Jadwal.objects.all()
    hasilku = Jadwalku(request.POST or None)  
    context = {
        'form' : formku,
        'form_status':hasilku,
    }

    if request.method=='POST':
	    if hasilku.is_valid():
		    formku.create(
			    Dosen = hasilku.cleaned_data.get('Dosen'),
			    Matkul = hasilku.cleaned_data.get('Matkul'),
                JumlahSKS = hasilku.cleaned_data.get('JumlahSKS'),
                Deskripsi = hasilku.cleaned_data.get('Deskripsi'),
                semestertahun = hasilku.cleaned_data.get('semestertahun'),
                ruangan = hasilku.cleaned_data.get('ruangan'),
			    )

    return render(request, 'comingsoon.html', context)

def delete(request, idinput) :
    Jadwal.objects.filter(id=idinput).delete()
    return HttpResponseRedirect("/project")

def detail(request, id_detail) :
   id_matkul = Jadwal.objects.get(id=id_detail)
   return render(request, 'detail.html', {'i': id_matkul})

homeku/templates/story1.html
<!-- <!DOCTYPE html>
<html>
    {% load static %}
<head>
<title>Bob-MyProfile</title>

<meta name="viewport" content="width=device-width"/>
<meta name="description" content="Raihan Blog"/>
<meta charset="UTF-8"> 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'homeku/style.css' %}">

<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700|Lato:400,300' rel='stylesheet' type='text/css'>


</head>
<body id="top">
	<section><nav class="navbar navbar-expand-lg navbar-light bg-transparent" id="mainNav">
		<div class="container">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
		  <ul class="navbar-nav ml-auto">
			<li class="nav-item">
			  <a class="nav-link" href="/">Homepage</a>
			</li>
		  </ul>
		</div>
	  </div>
	  </nav>
	</section> -->


	{%include 'base.html'%}

	{% block content%}

	{% load static %}

<div id="cv">
	<div class="mainDetails">
		<div id="headshot" class="quickFade">
			<img src="{%static '/homeku/IMG-20190301-WA0001.jpg'%}" alt="Fotoku" />
		</div>
		
		<div id="name">
			<h1>Muhammad Raihan Andriqa</h1>
			<h2>1906353574</h2>
		</div>
		<div class="clear"></div>
	</div>
	
	<div id="mainArea">
		<section>
			<article>
				<div class="sectionTitle">
					<h1>My Profile</h1>
				</div>
				
				<div class="sectionContent">
					<ul>
						<li>Nama Lengkap   : Muhammad Raihan Andriqa</li>
						<li>Tanggal Lahir  : 13 Mei 2001</li>
						<li>Golongan Darah : A</li>
						<li>Hobi 		   : Futsal dan Ngoding</li>
					</ul>
				</div>
			</article>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Education</h1>
			</div>
			
			<div class="sectionContent">
				<article>
					<h2>SMAN 68</h2>
					<p class="subDetails">2016 - 2019</p>
				</article>
				
				<article>
					<h2>Universitas Indonesia</h2>
					<p class="subDetails">2019 - Present</p>
				</article>
			</div>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>A brief of my Story</h1>
			</div>
			
			<div class="sectionContent">
				<article>
					<p>Halo dunia! kenalin, nama aku rehan. Aku biasa dipanggil Bob. Aku sekarang
						sedang menempuh pendidikan di Fakultas Ilmu Komputer, jurusan Sistem informasi.
						Aku sangat senang berada di fakultas ini. Doakan aku lulus tepat waktu ya....!
					</p>
				</article>
			</div>
			<div class="clear"></div>
		</section>

		<section>
			<div class="sectionTitle">
				<h1>Contact Me at...</h1>
			</div>
			
			<div class="sectionContent">
				<ul class="keySkills">
					<li></li>
					<li><a href="https://www.instagram.com/raihanandr/" target="_blank"><img src="{%static '/homeku/instagram.png'%}" width="50" height="50" alt="Instagram" /></a> </li>
					<li><a href="https://www.linkedin.com/in/muhammad-raihan-andriqa-4961691b3/" target="_blank"><img src="{%static '/homeku/linkedin.png'%}" width="50" height="50" alt="linkedin" /></a></li>
				</ul>
			</div>
			<div class="clear"></div>
		</section>
		
	</div>

	{% endblock %}

story3/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Hello, world!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link type="text/css" rel="stylesheet" href="{% static '../static/homeku/style.css' %}">
  </head>

  <body>
      
    <body id="top">
        <section><nav class="navbar navbar-expand-lg navbar-light bg-transparent" id="mainNav">
            <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="/">Homepage</a>
                </li>
              </ul>
            </div>
          </div>
          </nav>
        </section>


{% block content%}
{% endblock %}

  </body>

</html>

story3/templates/index.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Hello, world!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link type="text/css" rel="stylesheet" href="{% static '../static/homeku/style.css' %}">
  </head>

  <body class="page-top">
    <section><nav class="navbar navbar-expand-lg navbar-light bg-transparent" id="mainNav">
      <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%static '../static/homeku/my-cv.pdf'%}" download>CV<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="project/">Mata Kuliah</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="story1">Story 1</a>
          </li>
        </ul>
      </div>
    </div>
    </nav>
  </section>
    
<style>
/* accordion heading */
.accordion h1{
  font-size:26px;
  font-weight: normal;
  text-align: center;
  margin-bottom:0px;
  margin-top:0px;
  background-color:darkblue;
  padding-top:7px;padding-bottom:7px;
  border:1px solid darkgrey;
  border-radius:3px;
}
.accordion h1:hover{
  cursor:pointer;
}

.accordion div{
  display:none;
  padding:10px;
  height:200px;
  line-height:20px;
  border:1px solid gray;
  border-radius:3px;
}

.accordion-content{
margin-top: 10px;
margin-bottom: 20px;
margin-left: 10px;
font-weight: bold;
color: black;
font-size: large;
}

@media screen and (max-width:480px){
  .accordion{
      width:100%;
      margin:0;
  }
}


/* Style the buttons that are used to open and close the accordion panel */
.accordion {
background-color:antiquewhite;
color: #444;
cursor: pointer;
padding: 18px;
width: 100%;
text-align: center;
font-size: 20px;
border: none;
outline: none;
transition: 0.4s;
margin-bottom: 10px;
border-radius: 15px;

}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */


.reorder-up {
float: right;
font-size: 30px;
color: #00AA13;
margin-right: 20px;
}


.reorder-down {
float: right;
font-size: 30px;
color: #00AA13;
margin-right: 20px;
}

</style>
     

      <section class="jumbotron">
        <h1>Enjoy Surf</h1>
        <br><br>
        <p style="color: beige;">Know me from here....</p>
      </section>
     <h1 id="halo" style="font-size: 100px; text-align: center;"  >About Me</h1>


     <div class="wrapper">
      <div class="container p-5">
  
  
          <div class="ada">
              <button class="accordion text-footer">
                  
                  <a class="reorder-down">&#x25BC;</a>Aktivitas
                  <a class="reorder-up">&#x25B2;</a>
              </button>
              <div id="accordioncontent_1" class="accordion-content">
                  Aktivitas saya belakang ini adalah ngoding dan menonton drama korea. Saya
                  biasa menonton drama korea bersama teman-teman saya pada hari sabtu malam.
              </div>
          </div>
          
          <div class="ada">
            <button class="accordion text-footer">
                <a class="reorder-down">&#x25BC;</a>Kepanitiaan
                <a class="reorder-up">&#x25B2;</a>
            </button>
            <div id="accordioncontent_2" class="accordion-content">
                <li>HRD  Field Coordinator</li>
                <li>Penanggung Jawab Humas SIWAK 2020</li>
            </div>
        </div>

          <div class="ada">
              <button class="accordion text-footer">
                  <a class="reorder-down">&#x25BC;</a>Organisasi
                  <a class="reorder-up">&#x25B2;</a>
              </button>
              <div id="accordioncontent_2" class="accordion-content">
                  <li>Staff Pengabdian Masyarakt Bem Fasilkom UI </li>
                  <li>Staff Islam Learning Center FUKI FASILKOM UI </li>
              </div>
          </div>
  
          <div class="ada">
              <button class="accordion text-footer">
                  <a class="reorder-down">&#x25BC;</a>PRESTASI
                  <a class="reorder-up">&#x25B2;</a>
              </button>
              <div id="accordioncontent_3" class="accordion-content">
                  <table>
                    <th>
                    <ul>
                      <li>
                        peserta terbaik SBF Pengabdian Masyarakat FASILKOM UI 2019
                      </li>
                    </ul>
                  </th>
                  </table>
                  
                  
              </div>
          </div>
      </div>
  </div>
  
    

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
      $(document).ready(function () {
        $(".accordion-content").hide();
        $(".accordion").click(function () {
            var id = this.id;   /* getting heading id */
            /* looping through all elements which have class .accordion-content */
            $(this).next().toggle("slow");  /* Selecting div after h1 */
        });
    });


    $(".reorder-up").click(function () {
        var $current = $(this).closest('.ada')
        var $previous = $current.prev('.ada');
        if ($previous.length !== 0) {
            $current.insertBefore($previous).delay("slow").fadeIn();
        }
        return false;
    });

    $(".reorder-down").click(function () {
        var $current = $(this).closest('.ada')
        var $next = $current.next('.ada');
        if ($next.length !== 0) {
            $current.insertAfter($next).delay("slow").fadeIn();
        }
        return false;
    });

      
    </script>
      
    </body> 
</html>

sutori5/templates/comingsoon.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Hello, world!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link type="text/css" rel="stylesheet" href="{% static '../static/homeku/style.css' %}">
  </head>
<body>

  <body id="top">
    <section><nav class="navbar navbar-expand-lg navbar-light bg-transparent" id="mainNav">
        <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Homepage</a>
            </li>
          </ul>
        </div>
      </div>
      </nav>
    </section>

  <div class="container">

    <form action="" method="POST" novalidate>
      {% csrf_token %}
      {{form_status.as_p}}
      <input type="submit" value="SUBMIT"/>
    </form>



    <br><br><br>




      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Detail</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for i in  form %}
          <tr>
            <th scope="row">{{i.Matkul}}</a></th>
            <td><button type="button" class="btn btn-outline-dark"><a id="detail" href="{% url 'sutori5:detail' i.id %}" class="card-link">Detail Course</a></button></td>
            <td><button type="button" class="btn btn-outline-dark"><a id="delete" href="{% url 'sutori5:delete' i.id %}" class="card-link"> Delete Course</a></button></td>
          </tr>
          {% endfor %}
      </tbody>
    
      



</html>

sutori5/templates/detail.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    

    


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Hello, world!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link type="text/css" rel="stylesheet" href="{% static '../static/homeku/style.css' %}">
  </head>

  <body>
      
    <body id="top">
        <section><nav class="navbar navbar-expand-lg navbar-light bg-transparent" id="mainNav">
            <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="/project">Back</a>
                </li>
              </ul>
            </div>
          </div>
          </nav>
        </section>


        <div class="container">

          <div class="card">
            <h1 class="card-header">{{i.Matkul}}</h1>
            <div class="card-block">
            </div>
          </div>
          <br><br><br>

        <div class="card ">
          <div class="card-block">
            <br>
            <h6 class="card-subtitle mb-2 text-muted">Dosen    :{{i.Dosen}}</h6>
            <br>
            <h6 class="card-subtitle mb-2 text-muted">Jumlah SKS: {{i.JumlahSKS}}</h6>
            <br>
            <h6 class="card-subtitle mb-2 text-muted">Ruang Kelas: {{i.ruangan}}</h6>
            <br>
            <h6 class="card-subtitle mb-2 text-muted">Semester: {{i.semestertahun}}</h6>
            <br>
            <p>Deskripsi :</p>
            <p class="card-text">
              {{i.Deskripsi}}
            </p>
          </div>
        </div>
       
       
        </div>
    


      


  </body>

</html>